version: '3'

services:
  mariadb:
    image: mariadb
    container_name: api-fastify
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: swapi
      MYSQL_USER: toor
      MYSQL_PASSWORD: toor  
    ports:
      - "3306:3306"  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: api-rest-fastify
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root  
      PMA_PASSWORD: root  
    ports:
      - "8080:80" 
    depends_on:
      - mariadb  
