INSERT INTO `starship` VALUES
('[]','60','corvette','2.0','resources.starship',2),
('[]','60','Star Destroyer','2.0','resources.starship',3),
('[]','70','landing craft','1.0','resources.starship',5),
('[]','10','Deep Space Mobile Battlestation','4.0','resources.starship',9),
('["13","14","25","31"]','75','Light freighter','0.5','resources.starship',10),
('[]','80','assault starfighter','1.0','resources.starship',11),
('["1","9","18","19"]','100','Starfighter','1.0','resources.starship',12),
('["4"]','105','Starfighter','1.0','resources.starship',13),
('[]','40','Star dreadnought','2.0','resources.starship',15),
('[]','20','Medium transport','4.0','resources.starship',17),
('["22"]','70','Patrol craft','3.0','resources.starship',21),
('["1","13","14"]','50','Armed government transport','1.0','resources.starship',22),
('[]','40','Escort ship','2.0','resources.starship',23),
('[]','60','Star Cruiser','1.0','resources.starship',27),
('["29"]','120','Starfighter','1.0','resources.starship',28),
('[]','91','Assault Starfighter','2.0','resources.starship',29),
('[]','unknown','Space cruiser','2.0','resources.starship',31),
('[]','unknown','Droid control ship','2.0','resources.starship',32),
('["11","35","60"]','unknown','Starfighter','1.0','resources.starship',39),
('["39"]','unknown','yacht','1.8','resources.starship',40),
('["44"]','unknown','Space Transport','1.5','resources.starship',41),
('[]','unknown','Diplomatic barge','0.7','resources.starship',43),
('[]','unknown','freighter','unknown','resources.starship',47),
('["10","58"]','unknown','Starfighter','1.0','resources.starship',48),
('["35"]','unknown','yacht','0.9','resources.starship',49),
('[]','unknown','assault ship','0.6','resources.starship',52),
('[]','unknown','yacht','1.5','resources.starship',58),
('["10","11"]','unknown','capital ship','1.5','resources.starship',59),
('[]','unknown','transport','1.0','resources.starship',61),
('[]','unknown','star destroyer','1.0','resources.starship',63),
('["10","35"]','unknown','yacht','0.5','resources.starship',64),
('["10","11"]','unknown','starfighter','1.0','resources.starship',65),
('[]','100','starfighter','1.0','resources.starship',66),
('[]','unknown','cruiser','1.0','resources.starship',68),
('["10","79"]','unknown','starfighter','6','resources.starship',74),
('[]','unknown','starfighter','1.0','resources.starship',75);
