INSERT INTO `vehicles` VALUES
('wheeled','[]','resources.vehicle',4),
('repulsorcraft','[]','resources.vehicle',6),
('repulsorcraft','[]','resources.vehicle',7),
('starfighter','[]','resources.vehicle',8),
('airspeeder','["1","18"]','resources.vehicle',14),
('space/planetary bomber','[]','resources.vehicle',16),
('assault walker','[]','resources.vehicle',18),
('walker','["13"]','resources.vehicle',19),
('repulsorcraft','[]','resources.vehicle',20),
('sail barge','[]','resources.vehicle',24),
('repulsorcraft cargo skiff','[]','resources.vehicle',25),
('starfighter','[]','resources.vehicle',26),
('speeder','["1","5"]','resources.vehicle',30),
('starfighter','[]','resources.vehicle',33),
('repulsorcraft','[]','resources.vehicle',34),
('repulsorcraft','[]','resources.vehicle',35),
('repulsorcraft','[]','resources.vehicle',36),
('landing craft','[]','resources.vehicle',37),
('submarine','["10","32"]','resources.vehicle',38),
('speeder','["44"]','resources.vehicle',42),
('repulsorcraft','["11"]','resources.vehicle',44),
('airspeeder','["70"]','resources.vehicle',45),
('airspeeder','["11"]','resources.vehicle',46),
('gunship','[]','resources.vehicle',50),
('gunship','[]','resources.vehicle',51),
('walker','[]','resources.vehicle',53),
('walker','[]','resources.vehicle',54),
('speeder','["67"]','resources.vehicle',55),
('transport','[]','resources.vehicle',56),
('starfighter','[]','resources.vehicle',57),
('wheeled walker','["79"]','resources.vehicle',60),
('fire suppression ship','[]','resources.vehicle',62),
('droid starfighter','[]','resources.vehicle',67),
('airspeeder','[]','resources.vehicle',69),
('air speeder','[]','resources.vehicle',70),
('wheeled walker','[]','resources.vehicle',71),
('droid tank','[]','resources.vehicle',72),
('airspeeder','[]','resources.vehicle',73),
('walker','[]','resources.vehicle',76);
